[package]
name = "algotoken"
version = "1.0.0"
authors = []

[addresses]
algotoken = "0x580ab668ae920138bb0c9d7a953e066be06b025ed819ead7cc083b17a99536fd"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "aptos-node-v1.19.0"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]